### PR TITLE
General Structure of Project - New Main

### PR DESCRIPTION
**Pull request by zlatica-pernar**
main was testcode for repository initialization. 

deleted old main, general structure: added classes Board, Player and TicTacToe. most methods still empty and ready for implementation with feature branches/user stories.

### CODE REVIEW

**Comment by EmilAtic** [comment]
test package missing

**Review by EmilAtic — DISMISSED** [review]
add test package

**Comment by valentinaskn** [comment]
please exclude board logic

**Comment by zlatica-pernar** [comment]
added test package and deleted board logic

**Review by valentinaskn — APPROVED** [review]
All checks out. Let's merge this! 🚀

**Pull request merged**
